<?php
/**
 * AssoLife Configuration
 * This file loads the generated configuration or provides defaults
 */

// Check if configuration was generated by installer
if (file_exists(__DIR__ . '/config.generated.php')) {
    return require __DIR__ . '/config.generated.php';
}

// Default configuration (installer will generate config.generated.php)
return [
    'db' => [
        'host'     => 'localhost',
        'dbname'   => 'associazione',
        'username' => 'root',
        'password' => '',
        'charset'  => 'utf8mb4',
        'prefix'   => '',
    ],
    'app' => [
        'name'         => 'Associazione',
        'version'      => '1.0.0',
        'base_path'    => '/public/',
        'force_https'  => false,
        'session_name' => 'assolife_session',
        'timezone'     => 'Europe/Rome',
    ],
    'email' => [
        'enabled'     => false,
        'smtp_host'   => 'smtp.example.com',
        'smtp_port'   => 587,
        'smtp_user'   => '',
        'smtp_pass'   => '',
        'smtp_secure' => 'tls', // tls o ssl
        'from_email'  => 'noreply@associazione.it',
        'from_name'   => 'AssoLife',
    ],
];