<?php
/**
 * AssoLife Configuration
 * This file is generated by the installer
 */

// Check if configuration exists
if (file_exists(__DIR__ . '/config.generated.php')) {
    return require __DIR__ . '/config.generated.php';
}

// Default configuration (installer will generate the real one)
return [
    'db' => [
        'host'     => 'localhost',
        'dbname'   => 'associazione',
        'username' => 'root',
        'password' => '',
        'charset'  => 'utf8mb4',
        'prefix'   => '',
    ],
    'app' => [
        'name'         => 'Associazione',
        'version'      => '1.0.0',
        'base_path'    => '/public/',
        'force_https'  => false,
        'session_name' => 'assolife_session',
        'timezone'     => 'Europe/Rome',
    ],
];